### ISSUE TITLE
window render

### ISSUE THREAD

**Issue by sadek-hussein** [micro-frontends-demo/container#12] opened 2019-11-19 09:47 UTC
kindly you can advice about the below :
```
TypeError: window["render".concat(...)] is not a function

 34 |   window[`render${name}`](`${name}-container`, history);
```

**Comment by camjackson** [comment] 2019-11-19 09:57
I'm not sure, if you'd like help you'll need to provide a bit more context:
- what are you trying to do?
- what steps have you taken?
- what do you expect to happen?
- what actually happens?

From the error you posted above it looks like the template string is being compiled down to a `String.concat` call, but that function isn't supported by the JS engine you're using. Which makes no sense as concat is very well supported: https://caniuse.com/#feat=mdn-javascript_builtins_string_concat

**Comment by sadek-hussein** [comment] 2019-11-19 10:03
the renderMicroFrontend function return this error in your upload project "Container"

**Comment by sadek-hussein** [comment] 2019-11-19 10:04
this is the function:
 renderMicroFrontend = () => {
    const { name, window, history } = this.props; 
    window[`render${name}`](`${name}-container`, history);
  };

**Comment by camjackson** [comment] 2019-11-19 10:11
So that function should only run *after* a micro frontend has been downloaded and fired its `onload` event. And reading the error again, it seems that it's `window.renderWhatever` that is not a function. Which would indicate that the micro frontend failed to attach its entry-point function into the global scope.

I don't know why that would happen, I haven't seen it before. I would suggest you debug by putting `console.log` statements throughout the container code to see which micro frontend is failing to load, and then put logs through that micro frontend's code to see why it's not working properly.

**Comment by sadek-hussein** [comment] 2019-11-19 11:38
nothing ... the container project does not work... mainly the problem from  render micro frontend

**Comment by camjackson** [comment] 2019-11-27 08:32
I've just done a fresh clone of the four repos, installed and built them, and everything works as expected. It's also running fine in production [here](https://demo.microfrontends.com). So I'm going to close this issue as I really don't have enough information to be able to reproduce or debug it.

If you're able to debug it further, take the code apart, and get more specific about what exactly isn't working for you, feel free to open another issue and we can take it from there.

**Closed by camjackson** 2019-11-27 08:32 UTC

**Comment by myszon01** [comment] 2019-12-05 05:12
E
